name: rental_mobil_app
description: Aplikasi Rental Mobil

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Icon bawaan Flutter (WAJIB)
  cupertino_icons: ^1.0.6

  # HTTP request ke Laravel
  http: ^1.1.0

  # Simpan token login
  shared_preferences: ^2.2.2

  # State management
  provider: ^6.1.1

  # Format tanggal & mata uang
  intl: ^0.19.0

  # Upload foto
  image_picker: ^1.0.7

  # Cache gambar dari internet
  cached_network_image: ^3.3.1

  # Rating bintang
  flutter_rating_bar: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true  # ← INI YANG PALING PENTING